#
# Copyright (c) 2021 Airbyte, Inc., all rights reserved.
#

URL_SCHEMA = {"organizations": {"org_id": {"employees": {"employee_id": {"bank_accounts": {}}}, "teams": {}}}}


TYPES_SCHEMA_DICT = {
    "organisations": {
        "id": "UUID",
        "name": "STRING",
        "phone": "STRING",
        "country": "STRING",
        "logo_url": "STRING",
        "primary_address": "STRING",
        "end_of_week": "STRING",
        "typical_work_day": "STRING",
        "payroll_admin_emails": "ARRAY",
        "subscription_plan": "STRING",
        "superfund_name": "STRING",
        "employees_count": "NUMBER",
        "active_employees_count": "NUMBER",
        "pending_employees_count": "NUMBER",
        "time_zone": "STRING",
        "created_at": "STRING",
    },
    "employees": {
        "id": "UUID",
        "account_name": "STRING",
        "title": "STRING",
        "role": "STRING",
        "first_name": "STRING",
        "last_name": "STRING",
        "middle_name": "STRING",
        "address": "STRING",
        "avatar_url": "STRING",
        "known_as": "STRING",
        "job_title": "STRING",
        "gender": "STRING",
        "country": "STRING",
        "date_of_birth": "STRING",
        "martial_status": "STRING",
        "personal_email": "STRING",
        "personal_mobile_number": "STRING",
        "home_phone": "STRING",
        "employing_entity": "STRING",
        "location": "STRING",
        "company_email": "STRING",
        "company_mobile": "STRING",
        "start_date": "STRING",
        "termination_date": "STRING",
        "secondary_cost_centre": "STRING",
        "primary_manager": "OBJECT",
        "secondary_manager": "OBJECT",
        "external_id": "STRING",
    },
    "leave_requests": {
        "id": "UUID",
        "start_date": "STRING",
        "total_hours": "NUMBER",
        "comment": "STRING",
        "status": "STRING",
        "leave_balance_amount": "NUMBER",
        "leave_category_name": "STRING",
        "reason": "STRING",
        "employee_id": "STRING",
    },
    "timesheet_entries": {"employee_id": "UUID", "org_id": "UUID", "start_date": "STRING", "end_date": "STRING"},
    "employment_histories": {"id": "UUID", "title": "STRING", "start_date": "STRING", "end_date": "STRING", "employment_type": "STRING"},
    "emergency_contacts": {
        "id": "UUID",
        "contact_name": "STRING",
        "daytime_contact_number": "STRING",
        "after_hours_no": "STRING",
        "after_nobile_no": "STRING",
        "relationship": "STRING",
        "contact_type": "STRING",
    },
    "teams": {"id": "UUID", "name": "STRING", "status": "STRING"},
    "bank_accounts": {
        "id": "UUID",
        "accoutn_name": "STRING",
        "account_number": "STRING",
        "bsb": "STRING",
        "amount": "STRING",
        "primary_account": "BOOLEAN",
    },
    "certifications": {"id": "STRING", "name": "STRING", "type": "STRING"},
    "payslips": {
        "tax": "NUMBER",
        "name": "STRING",
        "address_line_1": "STRING",
        "address_line_2": "STRING",
        "suburb": "STRING",
        "postcode": "STRING",
        "address_state": "STRING",
        "note": "STRING",
        "post_tax_deducation": "NUMBER",
        "pre_tax_deduction": "NUMBER",
        "business_name": "STRING",
        "business_address": "STRING",
        "business_abn": "STRING",
        "base_rate": "NUMBER",
        "hourly_rate": "NUMBER",
        "pay_period_starting": "STRING",
        "pay_period_ending": "STRING",
        "base_rate_unit": "STRING",
        "employment_type": "STRING",
        "payroll_type": "STRING",
        "payment_date": "STRING",
    },
    "pay_details": {
        "id": "UUID",
        "effective_from": "STRING",
        "classification": "STRING",
        "industrial_instrument": "STRING",
        "pay_rate_template": "STRING",
        "anniversary_date": "STRING",
        "salary": "NUMBER",
        "salary_type": "STRING",
        "pay_unit": "STRING",
        "pay_category": "STRING",
        "leave_allowance_templa": "STRING",
        "change_reason": "STRING",
        "comments": "STRING",
    },
}
